### ISSUE TITLE
RIGHT_CLICK_BLOCK doesn't worked

### ISSUE THREAD

**Issue by charindo** [fuyutsuki/TapID#1]
多分`PlayerInteractEvent :: RIGHT_CLICK_BLOCK`って使えなくなった気が...

**Comment by fuyutsuki** [comment]
一応デバッグをした上でリリースをしているのですが、`PlayerInteractEvent::RIGHT_CLICK_BLOCK` が使えない @rindou96 さんの使用しているサーバーソフトのバージョンや、端末を教えていただけますか？

**Comment by fuyutsuki** [comment]
返信が無いのでclose
